#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,2,4,7,14,41,44,47,54,56,57,67&i=1,2,3,4,18,19,20,21,28,29,30,41&v=14,13,2,255,32,33,34,12,17,16,5,21 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ST7735 and ST7789 Library, OneButton, IRremoteESP8266 */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define DSP_MODEL			DSP_ST7789
#define TFT_DC			14
#define TFT_CS			13
#define TFT_RST			2
#define I2S_DOUT			255
#define VS1053_CS			32
#define VS1053_DCS			33
#define VS1053_DREQ			34
#define VS1053_RST			-1
#define ENC2_BTNR			17
#define ENC2_BTNL			16
#define ENC2_BTNB			5
#define ENC2_HALFQUARD			255
#define IR_PIN			21
#define L10N_LANGUAGE			RU


#endif
